import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../components/navbar/navbar'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const NavLinks = [
  { label: 'Home', href: '/home' },
  { label: 'Order', href: '/order' },
  { label: 'Billing', href: '/billing' },
  { label: 'Dashboard', href: '/dashboard' },
]

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={inter.className}>
      <body>
        <div className='main-container'>
          <Navbar NavLinks={NavLinks} />
          <main className='main-layout'>{children}</main>
        </div>
      </body>
    </html>
  )
}
