// app/home/layout.js

import { Inter } from 'next/font/google'

export const metadata = {
  title: 'Tajammul Mart | Login',
  description: 'Generated by create next app',
}
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default function HomeLayout({ children }) {
  return (
    <html className={inter.className}>
      <body>
        <div className='login-layout'>{children}</div>
      </body>
    </html>
  )
}
